- name: "Copy config for secret {{ item }}"
  copy:
    src: "git_key.xml"
    dest: "/var/lib/jenkins/git_key.xml"
  register: secret_copy

- name: "Add secret from {{ item }}"
  shell: "java -jar jenkins-cli.jar -auth admin:admin -s http://localhost:8080 create-credentials-by-xml system::system::jenkins _ < git_key.xml"
  args:
    chdir: /var/lib/jenkins
  when: secret_copy.changed
