---
## setup linux slave
- hosts: slave1
  become: yes
  roles:
    - role: geerlingguy.java
      vars:
        java_packages:
          - openjdk-11-jre
  tasks:
    - name: Install git to work with SCM-based pipeline
      apt:
        name: git
        state: present
    - name: Copy script for running Jenkins agent
      copy:
        src: "{{ item }}"
        dest: "/usr/bin/{{ item }}"
        mode: 0777
      loop:
        - run-jenkins-agent.sh

## setup windows slave
- hosts: slave2
  vars:
    ansible_winrm_scheme: http
  roles:
    - role: openjdk11jre-windows
  tasks:
    - name: Install git to work with SCM-based pipeline
      win_chocolatey:
        name: git
        state: present
    - name: Copy script for running Jenkins agent
      win_copy:
        src: "{{ item }}"
        dest: "C:\\Users\\vagrant\\{{ item }}"
      loop:
        - run-jenkins-agent.ps1

## setup master
- hosts: master
  become: yes
  roles:
    - role: geerlingguy.java
      vars:
        java_packages:
          - openjdk-11-jre
    - role: geerlingguy.jenkins
      vars:
        jenkins_plugins:
          - longName: OWASP Markup Formatter Plugin
            name: antisamy-markup-formatter
            version: '2.1'
          - longName: Font Awesome API Plugin
            name: font-awesome-api
            version: 5.15.4-1
          - longName: JQuery3 API Plugin
            name: jquery3-api
            version: 3.6.0-2
          - longName: Trilead API Plugin
            name: trilead-api
            version: 1.0.13
          - longName: Jenkins Mailer Plugin
            name: mailer
            version: '1.34'
          - longName: ECharts API Plugin
            name: echarts-api
            version: 5.1.2-11
          - longName: Popper.js API Plugin
            name: popper-api
            version: 1.16.1-2
          - longName: Jenkins Git client plugin
            name: git-client
            version: 3.9.0
          - longName: Structs Plugin
            name: structs
            version: '1.23'
          - longName: 'Pipeline: Step API'
            name: workflow-step-api
            version: '2.24'
          - longName: bouncycastle API Plugin
            name: bouncycastle-api
            version: '2.24'
          - longName: Ant Plugin
            name: ant
            version: '1.11'
          - longName: WMI Windows Agents Plugin
            name: windows-slaves
            version: '1.8'
          - longName: Jenkins Parameterized Trigger plugin
            name: parameterized-trigger
            version: '2.41'
          - longName: Copy Artifact Plugin
            name: copyartifact
            version: 1.46.2
          - longName: Javadoc Plugin
            name: javadoc
            version: '1.6'
          - longName: Token Macro Plugin
            name: token-macro
            version: 266.v44a80cf277fd
          - longName: Caffeine API Plugin
            name: caffeine-api
            version: 2.9.2-29.v717aac953ff3
          - longName: Credentials Plugin
            name: credentials
            version: 2.6.1
          - longName: Conditional BuildStep
            name: conditional-buildstep
            version: 1.4.1
          - longName: built-on-column
            name: built-on-column
            version: '1.1'
          - longName: 'Pipeline: Supporting APIs'
            name: workflow-support
            version: '3.8'
          - longName: Popper.js 2 API Plugin
            name: popper2-api
            version: 2.10.1-1
          - longName: Environment Injector Plugin
            name: envinject
            version: 2.4.0
          - longName: Matrix Project Plugin
            name: matrix-project
            version: '1.19'
          - longName: Command Agent Launcher Plugin
            name: command-launcher
            version: '1.6'
          - longName: Plain Credentials Plugin
            name: plain-credentials
            version: '1.7'
          - longName: Bootstrap 5 API Plugin
            name: bootstrap5-api
            version: 5.1.1-1
          - longName: Oracle Java SE Development Kit Installer Plugin
            name: jdk-tool
            version: '1.5'
          - longName: SCM API Plugin
            name: scm-api
            version: 2.6.5
          - longName: Maven Integration plugin
            name: maven-plugin
            version: '3.12'
          - longName: Bootstrap 4 API Plugin
            name: bootstrap4-api
            version: 4.6.0-3
          - longName: 'Pipeline: SCM Step'
            name: workflow-scm-step
            version: '2.13'
          - longName: Matrix Authorization Strategy Plugin
            name: matrix-auth
            version: 2.6.8
          - longName: SSH Credentials Plugin
            name: ssh-credentials
            version: '1.19'
          - longName: Display URL API
            name: display-url-api
            version: 2.3.5
          - longName: EnvInject API Plugin
            name: envinject-api
            version: '1.7'
          - longName: Plugin Utilities API Plugin
            name: plugin-util-api
            version: 2.4.0
          - longName: Snakeyaml API Plugin
            name: snakeyaml-api
            version: 1.29.1
          - longName: Script Security Plugin
            name: script-security
            version: '1.78'
          - longName: Jenkins JSch dependency plugin
            name: jsch
            version: 0.1.55.2
          - longName: Jenkins Multijob plugin
            name: jenkins-multijob-plugin
            version: '1.36'
          - longName: 'Pipeline: Job'
            name: workflow-job
            version: '2.41'
          - longName: Jenkins Apache HttpComponents Client 4.x API Plugin
            name: apache-httpcomponents-client-4-api
            version: 4.5.13-1.0
          - longName: 'Pipeline: API'
            name: workflow-api
            version: '2.46'
          - longName: Jackson 2 API Plugin
            name: jackson2-api
            version: 2.12.4
          - longName: SSH server
            name: sshd
            version: 3.1.0
          - longName: Credentials Binding Plugin
            name: credentials-binding
            version: '1.27'
          - longName: JAXB plugin
            name: jaxb
            version: 2.3.0.1
          - longName: Run Condition Plugin
            name: run-condition
            version: '1.5'
          - longName: Jenkins Git plugin
            name: git
            version: 4.8.2
          - longName: External Monitor Job Type Plugin
            name: external-monitor-job
            version: '1.7'
          - longName: Checks API plugin
            name: checks-api
            version: 1.7.2
          - longName: JUnit Plugin
            name: junit
            version: '1.53'

## setup demo git repository
- hosts: master
  become: yes
  roles:
    - role: daveol.git_server
      vars:
        git_keys:
          - "{{ user_git_public_key }}"
          - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLHvdSCWaPYBDoYh/yVMxfSDlH3un8NdDrqFC55YYIKTqaa40TSk9AWEe8/wDNcw1emyqP8ed1rtGVtevyxRWyo=
        git_repos:
          - path: test.git

- hosts: master
  become: yes
  tasks:
    - name: Get jenkins-cli.jar
      get_url:
        url: http://localhost:8080/jnlpJars/jenkins-cli.jar
        dest: /var/lib/jenkins/jenkins-cli.jar
      retries: 3 # wait till restart completes
      delay: 15

    - name: Add slaves
      include_tasks: add-slave.yml
      loop:
        - linux-slave.xml
        - windows-slave.xml

    - name: Add secret (git private key) for pipeline
      include_tasks: add-secret.yml
      loop:
        - git_key.xml
