- job:
    name: 'multibranch_variant'
    project-type: multibranch
    periodic-folder-trigger: 1m
    script-path: Jenkinsfile
    scm:
      - git:
          url: git@192.168.50.100:test.git
          credentials-id: git_key
          discover-tags: true
